page-description: Who we are
title: Who We Are
body:   |
        <p>We are a team of scientists who have been frustrated by the lack of affordable and easy-to-use data acquisition device to provide an interface between a modern computer and older analog instruments.</p>
        <p>The idea of making our own data acquisition device originated while working with <a href='http://www.opticalfibersystems.com'>Optical Fiber Systems Inc</a> and <a href='http://www.sensorica.co/'>Sensorica</a>.</p>
